### ISSUE TITLE
Prebuild tokens associated to a certains client_id

### ISSUE THREAD

**Issue by zauddelig** [bitpay/bitpay-python-py2#13]
To my understading o the API the token associate an API client to an account, the client is then identified by its id, i.e. through its public key.

Now why the tokens cannot be prebuilt through the /tokens GET service if it actually returns something? One should add something like this inside the `Client` class: 

``` python
xidentity = key_utils.get_compressed_public_key_from_pem(self.pem)
xsignature = key_utils.sign(self.uri+"/tokens", self.pem)
headers = {....}
for token in request.get(self.uri + "/tokens", headers=headers).json()["data"]: 
     self.tokens.update(token)
```

**Comment by philosodad** [comment]
There is an equivalent method in the Ruby library and we may move this into the libraries in general.

**Comment by zauddelig** [comment]
Strangely enough there are two methods that do this in a sightly similar ways yet the first does not actually change the @tokens property:

``` ruby
## Pair client with BitPay service
      # => Pass empty hash {} to retreive client-initiated pairing code
      # => Pass {pairingCode: 'WfD01d2'} to claim a server-initiated pairing code
      #
      def pair_client(params={})
        tokens = post(path: 'tokens', params: params)
        return tokens["data"]
      end
```

``` ruby
    ## Fetches the tokens hash from the server and
    #  updates @tokens
    #
    def refresh_tokens
      response = get(path: 'tokens')["data"]
      token_array = response || {}
      tokens = {}
      token_array.each do |t|
        tokens[t.keys.first] = t.values.first
      end
      @tokens = tokens
      return tokens
    end
```

I suppose it is due to giving tokens knowledge both to client and rest connector, anyway inyour opinion what's the more proper name between `refresh_tokens` and `pair_client`?

**Comment by philosodad** [comment]
One of these is a post, it creates a token on the server, the other is a get, it gets previously created tokens from the server. So they do very different things. If I'm not mistaken, the refresh tokens method is private.

I'd actually prefer that neither changed the @tokens property, because I'm not a huge fan of side effects in methods and I'm trying to get all of the libraries into a more functional style.

**Comment by zauddelig** [comment]
See how it's easy to mismatch the HTTP methods if one has to read from the code? :)

Anyway I guess the very same functionality as in Ruby could be attained like this:

``` python
_tokens = None

@property
def tokens(self):
    if not self._tokens:
        self._tokens = {}
        xidentity = key_utils.get_compressed_public_key_from_pem(self.pem)
        xsignature = key_utils.sign(self.uri+"/tokens", self.pem)
        headers = {....}
        for token in request.get(self.uri + "/tokens", headers=headers).json()["data"]: 
            self._tokens.update(token)
    return self._tokens

@tokens.setter
def set_tokens(self, tokens):
     self._tokens = tokens
```

**Comment by anbugal** [comment]
This repository is no longer maintained, please, refer to https://github.com/bitpay/bitpay-python
